services:

  # PostgreSQL para svc-menu
  postgres-menu:
    image: postgres:16-alpine
    container_name: postgres-menu
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_menu
    volumes:
      - menu_data:/var/lib/postgresql/data
    networks:
      - restaurante-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_menu"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL para svc-orders
  postgres-orders:
    image: postgres:16-alpine
    container_name: postgres-orders
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_orders
    volumes:
      - orders_data:/var/lib/postgresql/data
    networks:
      - restaurante-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_orders"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Microservicio svc-menu
  svc-menu:
    build: ./svc-menu
    container_name: svc-menu
    restart: unless-stopped
    expose:
      - "8081"
    environment:
      - DB_HOST=postgres-menu
      - DB_PORT=5432
      - DB_NAME=db_menu
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      postgres-menu:
        condition: service_healthy
    networks:
      - restaurante-net

  # Microservicio svc-orders
  svc-orders:
    build: ./svc-orders
    container_name: svc-orders
    restart: unless-stopped
    expose:
      - "8082"
    environment:
      - DB_HOST=postgres-orders
      - DB_PORT=5432
      - DB_NAME=db_orders
      - DB_USER=postgres
      - DB_PASS=postgres
      - MENU_SERVICE_URL=http://svc-menu:8081
    depends_on:
      postgres-orders:
        condition: service_healthy
      svc-menu:
        condition: service_started
    networks:
      - restaurante-net

  # Nginx API Gateway
  nginx:
    image: nginx:alpine
    container_name: nginx-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - svc-menu
      - svc-orders
    networks:
      - restaurante-net

networks:
  restaurante-net:
    driver: bridge

volumes:
  menu_data:
  orders_data:
