events {
    worker_connections 1024;
}

http {

    upstream svc_menu   { server svc-menu:8081; }
    upstream svc_orders { server svc-orders:8082; }

    server {
        listen 8080;

        # Rutas hacia svc-menu
        location /api/menu/ {
            proxy_pass         http://svc_menu/api/menu/;
            proxy_set_header   Host             $host;
            proxy_set_header   X-Real-IP        $remote_addr;
            proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
            proxy_read_timeout 30s;
        }

        # Rutas hacia svc-orders
        location ~ ^/api/orders {
                    proxy_pass         http://svc_orders;
                    proxy_set_header   Host             $host;
                    proxy_set_header   X-Real-IP        $remote_addr;
                    proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
                    proxy_read_timeout 30s;
        }
    }
}
